name: 🐛 Bug Report
description: Report a bug or unexpected behavior in globus-go-gcs
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: dropdown
    id: persona
    attributes:
      label: Who are you?
      description: What's your primary role?
      options:
        - System Administrator
        - Data Manager
        - Research PI
        - IT Manager
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        When I run `globus-connect-server endpoint show`, I get an error...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command `globus-connect-server endpoint show`
        2. See error message `...`
        3. Expected to see `...`
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The command should display endpoint details...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: |
        Error: endpoint not found
        ...full error output...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: Ubuntu 22.04
        - Go version: 1.21.5
        - globus-go-gcs version: v0.1.0
        - GCS endpoint version: v5.4.60
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please include any relevant log output or error messages
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable)
        - High (major functionality broken)
        - Medium (feature impaired but workaround exists)
        - Low (minor issue, minimal impact)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        This worked in Python GCS CLI v5.4.60...
        Related to issue #123...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have included all relevant information (environment, logs, steps)
          required: true
